### ISSUE TITLE
Is this only a demo page without any experiment source code?

### ISSUE THREAD

**Issue by whitewum** [CraftJarvis/RAT#1]
The experiments in the paper show great improvements in many groups, Code Generation, Mathematical Reasoning, Math Reasoning, etc.   Are these codes avaible to see the experiments  details.

THX.

**Comment by zhwang4ai** [comment]
Since the RAT (Retrieval Augmented Thoughts) methods leverage various corpora for tasks like code generation, math reasoning, and embodied planning, drawn from internet web pages or GitHub repositories, we must adhere to the open-source guidelines of these communities. Therefore, we have currently only released the code for open-ended creative writing in `creative.ipynb` for public testing. However, we've detailed other experimental setups, including prompts and corpus sources, in our paper. We are also in the process of organizing and releasing code that complies with open-source licenses, and will update this repository accordingly.
